### ISSUE TITLE
Fails on "addons.mozilla.org".

### ISSUE THREAD

**Issue by M-Reimer** [sorz/accept-language-per-site#2]
I want "addons.mozilla.org" to always get "Accept-Language" set to "en".
Your addon seems to work (tried for google.com) but doesn't modify "addons.mozilla.org".
Is this a upstream bug?

**Comment by sorz** [comment]
It's a upstream feature.
Firefox doesn't allow any extension to modify "addons.mozilla.org".

**Comment by M-Reimer** [comment]
I totally forgot that I still had this issue open. As far as I remember Mozilla now even allows to whitelist Add-ons to be able to process "protected" websites.
