### ISSUE TITLE
List existing rules

### ISSUE THREAD

**Issue by FranklinYu** [sorz/accept-language-per-site#3]
Would be nice if I can see a list of existing rules in the preference page. Even better if I can delete one or more rules.

**Comment by sorz** [comment]
Hi, rules are listed in extension's options on `about:addons`. What do you mean by *the preference page*?

**Comment by FranklinYu** [comment]
Sorry, my bad. I don’t know why it didn’t show there last time.

**Comment by sorz** [comment]
It's OK. :)
