### ISSUE TITLE
Make available in Firefox for Android?

### ISSUE THREAD

**Issue by zgll2022** [sorz/accept-language-per-site#7]
Hello, 

First of all I wanted to thank you for this extension. It works really well, and is a lifesaver in terms of privacy and anonymity for minority language users.

Recently, Mozilla has increased the number of extensions available for the Android version of Firefox.

I don't know exactly what changes need to be made, I think the manifest needs to be adapted to version 3, but it would be great to have this extension on Android, where you can't choose the language to be sent as Accept-language, it's taken from the OS directly.... :(

Right now I'm using your extension on Android through a collection, but it would be more convenient if it was officially available.

Thank you very much again and best regards.

**Comment by sorz** [comment]
Hi,

I'm glad to hear that you found it useful!

Actually, I've never tried it on mobile before. It seems it does not show up in the "Firefox for Android extensions" search. But if I go to the desktop extension page, I can install and use it on Android. Hmm...

I'm looking into how to migrate it to MV3. There are significant changes in the related API, but it seems doable. Stay tune :)

**Comment by sorz** [comment]
Turn out there is a Firefox for Android compatibility checkbox on add-ons upload page. I ticked it when upload the new version. Now it is listing on Android add-ons page.

**Comment by zgll2022** [comment]
Excellent! I have checked it and indeed I have been able to install it without any problem, and the extension works perfectly.

Thank you very much!
