### ISSUE TITLE
does not seem to work on Betterbird 118.0.1

### ISSUE THREAD

**Issue by riedel** [sorz/accept-language-per-site#8]
![grafik](https://github.com/sorz/accept-language-per-site/assets/566485/758fa077-bc2f-44ff-bc97-69ea7fc5d584)

I get:

```
GET / HTTP/2
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-GPC: 1
If-Modified-Since: Thu, 17 Oct 2019 07:18:26 GMT
If-None-Match: "3147526947"
TE: trailers
```

**Comment by riedel** [comment]
Seems to be a problem of betterbird which enforces more privacy and seems to override language setting after the addon.

**Comment by sorz** [comment]
![2024-01-02 185938](https://github.com/sorz/accept-language-per-site/assets/535565/b7d78b8f-988f-4b0a-a373-ee888bb74d2d)

I did not test the MV3 version on a brand new Firefox until now. Just found out this essential permission was turned off by default and Firefox didn't ask user to enable it on install. I should make the permission compulsory or at least tell user to enable it.
